#ifndef __KOAI__PREDICT_STRATEGY_TYPES__
#define __KOAI__PREDICT_STRATEGY_TYPES__

namespace strategy_types{
    enum PREDICT_STRATEGY{DEFAULT, WRESTLING_BIASED, STRIKING_BIASED};
}
#endif // ! __KOAI__PREDICT_STRATEGY_TYPES__ INCLUDED